name: netmock
description: A DevTools extension that enables developers to record, replay, and modify HTTP network responses directly within Flutter DevTools, eliminating the need for external proxy tools or backend modifications.
version: 0.0.1
homepage: https://github.com/Mastersam07/netmock

environment:
  sdk: ^3.8.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.0
  http: ^1.5.0
  devtools_extensions: ^0.4.0
  devtools_app_shared: ^0.4.0
  collection: ^1.19.1
  vm_service: ^15.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0