name: netmock_devtools_extension
description: DevTools extension for Netmock
version: 0.1.0

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  devtools_extensions: ^0.4.0
  devtools_app_shared: ^0.4.0
  dio: ^5.9.0
  vm_service: ^14.0.0
  collection: ^1.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true